void Rgrowthloop( double *p2, double *gp2, double *Io, double *r0, int *t,
	double *Hc, double *LAIF, double *kF, double *intF, double *slopeF, 
	double *APARout,

	double *h,
	double *hh,
	double *hC,
	double *hB,
	double *hBH,
	double *r,
	double *rB,
	double *rC,
	double *rBH,
	double *sw,
	double *vts,
	double *vt,
	double *vth,
	double *sa,
	double *la,
	double *ra,
	double *dr,
	double *xa,
	double *bl,
	double *br,
	double *bt,
	double *bts,
	double *bth,
	double *boh,
	double *bos,
	double *bo,
	double *bs,

	double *cs,
	double *clr,
	double *fl,
	double *fr,
	double *ft,
	double *fo,
	double *rfl,
	double *rfr,
	double *rfs,

	double *egrow,
	double *ex,
	double *rtrans,
	double *light,
	double *nut,
	double *deltas,
	double *LAI,
	int *status,
	//int *dim,
	int *lenvars,
	int *errorind,
  int *growth_st);